AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'europe.gemspec'

Style/SlicingWithRange:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false
